# Base layer
FROM node:20-alpine

# Set the working directory 
WORKDIR /app

# Copy over dependency files 
COPY package.json ./
COPY package-lock.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Create a .vite cache directory and set permissions
RUN mkdir -p node_modules/.vite && chmod -R 777 node_modules/.vite

# Copy all files 
COPY . .

# Expose the port
EXPOSE 3000

CMD ["npm", "run", "dev"]
